# Generated by Django 4.1.7 on 2023-04-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_video_free"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
