# Generated by Django 4.1.3 on 2023-06-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('videos', models.ManyToManyField(related_name='video_categories', to='videos.video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(related_name='category_videos', to='videos.category'),
        ),
    ]
