# Generated by Django 4.1.3 on 2023-12-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_category_video_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.TextField(),
        ),
    ]
