# Generated by Django 4.1.3 on 2024-06-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.URLField(blank=True, null=True)),
                ("features", models.JSONField()),
                ("metadata", models.JSONField()),
                ("frequency_type", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=21)),
                (
                    "paypal_plan_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_product_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
