# Generated by Django 4.1.3 on 2024-07-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_subscriptionplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
