# Generated by Django 4.1.3 on 2024-07-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_subscriptionplan_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="paypal_next_billing_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
