# Generated by Django 4.1.3 on 2024-07-23 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_subscriptionplan_paypal_next_billing_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="paypal_next_billing_time",
        ),
    ]
