version: '3.8'
services:
  core:
    build: .
    command: /start
    container_name: core
    volumes:
      - .:/usr/src/app
      - ./logs:/usr/src/app/logs
    ports:
      - 8009:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - core-db
  celery_worker:
    build: .
    image: satnam_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - core-db

  celery_beat:
    build: .
    image: satnam_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - core-db

  flower:
    build: .
    image: satnam_celery_flower
    command: /start-flower
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    ports:
      - 5557:5555
    depends_on:
      - redis
      - core-db
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  core-db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=oscar
      - POSTGRES_PASSWORD=17dejunio
      - POSTGRES_DB=core_dev
 
  satnam-client:
    build:
      context: ../client
    command:   yarn start
    container_name: satnam-client
    depends_on:
      - core
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://127.0.0.1:8009 
    ports:
      - 3001:3000
    stdin_open: true
    volumes: 
      - ../client:/usr/src/app

volumes:
  postgres_data:
  redis_data: