version: '3.8'
services:
  core:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8009:8000
    env_file:
      - ./.env.dev
    depends_on:
      - core-db
  core-db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=oscar
      - POSTGRES_PASSWORD=17dejunio
      - POSTGRES_DB=core_dev

volumes:
  postgres_data: