version: '3.8'
services:
  core:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: core
    volumes:
      - .:/usr/src/app
    ports:
      - 8009:8000
    env_file:
      - ./.env.dev
    depends_on:
      - core-db
  core-db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=oscar
      - POSTGRES_PASSWORD=17dejunio
      - POSTGRES_DB=core_dev
  satnam-client:
    build:
      context: ../satnam_front
    command:  yarn start
    container_name: satnam-client
    depends_on:
      - core
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://localhost:8009 
    ports:
      - 3001:3000
    stdin_open: true
    volumes: 
      - ../satnam_front:/usr/src/app

volumes:
  postgres_data: