# Generated by Django 4.1.7 on 2023-05-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_customuser_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stripe_subscription_id",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
