# Generated by Django 4.1.3 on 2024-07-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_trialdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="paypal_subscription_id",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
