# Generated by Django 4.1.3 on 2024-07-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_customuser_paypal_subscription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="paypal_next_billing_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
